feat: companies sdk
bakaphp/kanvas-core-js pull request #110
Opened 2023-11-13 05:35 UTC by FredPeal

2023-11-21 15:40 UTC, SparoHawk requested changes
**suggestion:** You should define paths for both `mutations` and `queries` in the `tsconfig.json` file in order to replace relative imports for more absolute ones. For example use `@mutations` instead of `../../mutations`.

2023-11-21 15:40 UTC, SparoHawk commented on package-lock.json
**issue(blocking):** Package management is done with Yarn, not NPM.

**suggestion:** Please remove this file and install or update packages with Yarn.

2023-11-21 15:40 UTC, SparoHawk commented on src/modules/companies-branches/index.ts
> +    return response.data.createCompanyBranch;
**question(non-blocking):** I see this function's return is not being cast as the expected return type. Is the casting not needed? Did you test to see if this works as intended?

2023-11-21 15:40 UTC, SparoHawk commented on src/modules/companies-branches/index.ts
> +    return response.data.updateCompanyBranch;
**question(non-blocking):** I see this function's return is not being cast as the expected return type. Is the casting not needed? Did you test to see if this works as intended?

2023-11-21 15:40 UTC, SparoHawk commented on src/modules/companies/index.ts
> +    return response.data.deleteCompany;
**question(non-blocking):** I see this function's return is not being cast as the expected return type. Is the casting not needed? Did you test to see if this works as intended?

2023-11-21 15:40 UTC, SparoHawk commented on src/mutations/companies-branches.mutation.ts
> +`;
**chore(blocking):** Correct code indentation please.

2023-11-21 15:40 UTC, SparoHawk commented on src/mutations/companies-branches.mutation.ts
> +`;
**chore(blocking):** Correct code indentation please.

2023-11-21 15:40 UTC, SparoHawk commented on src/queries/companies.query.ts
**chore(blocking):** Correct code indentation in this file please.

2023-11-21 15:40 UTC, SparoHawk commented on src/types/companies-branches.ts
**question(blocking):** Did you mark all optional properties as such? If not when trying to use these the developer will be required to provide the data.

2023-11-21 15:40 UTC, SparoHawk commented on src/types/companies.ts
**question(blocking):** Did you mark all optional properties as such? If not when trying to use these the developer will be required to provide the data.

2023-11-22 06:07 UTC, FredPeal commented
> **suggestion:** You should define paths for both `mutations` and `queries` in the `tsconfig.json` file in order to replace relative imports for more absolute ones. For example use `@mutations` instead of `../../mutations`.

That's not working for me. VS Code recognize the import but when I compiled the project, the terminal said "module `mutations` not found, I need help x)"

2023-12-09 00:59 UTC, SparoHawk approved these changes

2023-12-09 01:00 UTC, merged