feat: system modules query
bakaphp/kanvas-core-js pull request #115
Opened 2023-11-21 06:39 UTC by FredPeal

2023-12-07 17:30 UTC, RivierGrullon requested changes

2023-12-07 17:30 UTC, RivierGrullon commented on src/types/system-module.ts
> +export interface Where {
Suggestion: we already have a where condition named "WhereCondition" type that includes `column, operator, and value` you can modify that to get the "and" and de "or" but this argument should be optional

2023-12-07 17:30 UTC, RivierGrullon commented on src/modules/system-modules/index.ts
> +import { ClientType } from 'index';
Question(non-blocking): Doesn't this generate a circular import?

2023-12-09 01:29 UTC, SparoHawk commented
@FredPeal This commits has conflicts. Please resolve them.

2023-12-11 19:50 UTC, RivierGrullon approved these changes

2023-12-11 19:57 UTC, merged