Topics
bakaphp/kanvas-core-js pull request #117
Opened 2023-11-21 21:14 UTC by FredPeal

2023-12-09 01:31 UTC, SparoHawk commented
@FredPeal This commits has conflicts. Please resolve them.

2023-12-11 22:43 UTC, RivierGrullon requested changes

2023-12-11 22:43 UTC, RivierGrullon commented on src/mutations/topics.mutation.ts
> +export const UnFOLLOW_TOPIC_MUTATION = gql`
Change: uppercase here

2023-12-11 22:44 UTC, RivierGrullon commented on src/mutations/topics.mutation.ts
> +export const UnFOLLOW_TOPIC_MUTATION = gql`
Also please resolve the conflict changes

2023-12-12 13:56 UTC, RivierGrullon approved these changes

2023-12-12 14:55 UTC, merged