feat: social updates
bakaphp/kanvas-core-js pull request #267
Opened 2024-08-08 01:20 UTC by kaioken

- Add message view
- Add get user by displayname

2024-08-08 02:50 UTC, jerlyrosa approved these changes

2024-08-08 21:59 UTC, RivierGrullon requested changes

2024-08-08 21:59 UTC, RivierGrullon commented on src/queries/users.query.ts
> +  ) {    userByDisplayName(displayname: $displayName) {
change: format this template string pls

2024-08-13 19:57 UTC, RivierGrullon approved these changes

2024-08-14 12:30 UTC, kaioken commented on src/queries/users.query.ts
> +  ) {    userByDisplayName(displayname: $displayName) {
@RivierGrullon done

2024-08-14 14:21 UTC, RivierGrullon approved these changes

2024-08-14 14:34 UTC, buttercubz approved these changes

2024-08-15 12:54 UTC, merged