Feat/kp 63 Create new lead
bakaphp/kanvas-core-js pull request #32
Opened 2023-07-21 16:09 UTC by lizandro-mc

Create new lead from the SDK

2023-07-21 18:04 UTC, code-bryan requested changes

2023-07-21 18:04 UTC, code-bryan commented on src/modules/leads/index.ts
> +    console.log(response)
console.log

2023-07-21 18:07 UTC, lizandro-mc commented on src/modules/leads/index.ts
> +    console.log(response)
done

2023-07-22 16:00 UTC, code-bryan approved these changes

2023-07-24 16:24 UTC, RivierGrullon commented on src/types/leads.ts
> +  owner: Owner;
**Question:** If a user and the owner have the same attributes, why we are having 2 different interfaces?

2023-07-24 17:15 UTC, merged