draft: starting with users list
bakaphp/kanvas-core-js pull request #87
Opened 2023-10-03 07:38 UTC by FredPeal

2023-10-05 04:37 UTC, kaioken requested changes

2023-10-05 04:37 UTC, kaioken commented on src/mutations/userList.mutation.ts
> +      company {
@FredPeal no need for company

2023-10-05 04:37 UTC, kaioken commented on src/queries/usersLists.query.ts
> +        company {
@FredPeal no need for company

2023-10-05 04:37 UTC, kaioken commented on src/queries/usersLists.query.ts
> +          user {
@FredPeal no need for user email here just displyanem

2023-10-12 21:47 UTC, RivierGrullon approved these changes

2023-10-16 16:03 UTC, merged